name: Snyk Open Source Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master
        - name: Use Node.js for installing Snyk
          uses: actions/setup-node@v2
          with:
            node-version: 18.4
        
              # Install & prepare Snyk
        - run: npm install --location=global snyk
      
        - name: Setup Snyk
          env:
            SNYK_API: ${{ secrets.SNYK_API }}
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk auth "$SNYK_TOKEN"

        - name: Snyk Open Source Scanning
          env:
            SNYK_API: ${{ secrets.SNYK_API }}
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk test --org=${{ secrets.SNYK_ORG }} --all-projects
          continue-on-error: true

        - name: Snyk Open Source Monitor
          if: github.event_name == 'push'
          env:
            SNYK_API: ${{ secrets.SNYK_API }}
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk monitor --org=${{ secrets.SNYK_ORG }} --all-projects
          
