name: Snyk Open Source Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-analysis:
    name: 🛡️ Snyk Open Source Security Analysis
    runs-on: ubuntu-latest
    env:
      SNYK_API: https://api.us.snyk.io
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master
          
        - name: 🔧 Setup Snyk
          uses: snyk/actions/setup@master
          
        - name: Use Node.js for installing Snyk
          uses: actions/setup-node@v2
          with:
            node-version: 18.4

        - name: Snyk Open Source Scanning
          run: |
            echo "⏱️ Starting Snyk Container scan..."
            snyk test --org=${{ secrets.SNYK_ORG }} --all-projects
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     

    
          
